version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkinsnet

volumes:
  jenkins_data:

networks:
  jenkinsnet: